- name: Install debian packages
  apt:
    pkg:
      - python-pip
      - virtualenv
    state: present
- name: Install Magic Wormhole transit relay
  pip:
    name:
      - twisted
      - magic-wormhole-transit-relay
    virtualenv: /magic-wormhole-venv
- name: Install systemd unit
  copy:
    src: wormhole-tr.service
    dest: /etc/systemd/system/wormhole-re.service
  notify:
    - Enable systemd unit
